### ISSUE TITLE
Duvida sobre mensagem de Erro 

### ISSUE THREAD

**Issue by JoaoStefani** [lira92/buscacep#1]
Boa noite, 

Queria saber se você sabe se tem como colocar uma mensagem de erro tipo falando "CEP não encontrado".

E se tem como você me explicar o seu código fazendo favor. 

Att,

João Marcos Rodrigues Stefani

**Comment by lira92** [comment]
@JoaoStefani para exibir uma mensagem de erro você teria que implementar no seu callbak, por exemplo:
```javascript
$('#cep').on('blur', function() {
	buscacep.buscaPorCep($(this).val(), function(data) {
		if(data) {
                        // preenche o cep
                }
                else {
                        // exibe mensagem e limpa os campos
                }
	});
});
```

sobre explicar o código, sobre o que exatamente precisa que eu explique o src ou o código de exemplo do Readme?

**Comment by JoaoStefani** [comment]
Bom dia Alan,

Me desculpa pela a demora,
Mais eu coloquei o if mais não deu certo.

Da uma olhada no meu código:

$('#cep').on('blur', function() {
        buscacep.buscaPorCep($('#cep').val(), function(data) {
            if(data) {
                $("#endereco").val(data.logradouro);
                $("#endereco1").val(data.logradouro);
                $("#bairro").val(data.bairro);
                $("#cidade").val(data.localidade);
                $("#uf").val(data.uf);
            }else{
                aler('Teste');
            }
        });
    });

Em 9 de junho de 2017 11:25, Alan Lira <notifications@github.com> escreveu:

**Comment by lira92** [comment]
@JoaoStefani realmente havia um bug na lib, quando você coloca um cep inválido o viacep envia um json com "erro":true, e havia um if sem ação alguma dentro da lib, agora ele chama o callback, funcionando este if conforme você colocou no seu código acima, por favor se estiver usando o bower, execute um bower update. Obrigado.
